KS-4-3 added check if conditions are good for beans agriculture
Flex73/KotlinSprint pull request #28
Opened 2024-08-18 21:25 UTC by Flex73

2024-08-19 06:10 UTC, ievetrovdev requested changes
Почему `currentSeason` и `humidity`  ты сравниваешь, а `isWeatherSunny` и `isTentOpen` - нет?
Мы в константы записываем критерии, а потом  сравниваем с ними текущие условия.

2024-08-19 20:30 UTC, Flex73 commented
> Почему `currentSeason` и `humidity` ты сравниваешь, а `isWeatherSunny` и `isTentOpen` - нет? Мы в константы записываем критерии, а потом сравниваем с ними текущие условия.

isWeatherSunny и isTentOpen уже с типом Boolean, их можно сразу использовать в логическом выражении

2024-08-20 07:07 UTC, ievetrovdev requested changes
![image](https://github.com/user-attachments/assets/eacbb2f6-96e4-4901-80e2-b7703d8c117c)
У тебя изначальное были верно объявлены переменные `isWeatherSunny`  и  `isTentOpen` , которые имеют булевое значение. Теперь нужно добавить две константы с булевым значением, и их сравнивать, как ты это делаешь с переменными `humidity` и `currentSeason`

2024-08-20 19:02 UTC, ievetrovdev approved these changes
Хорошо, двигаемся дальше.

2024-08-20 19:11 UTC, merged