KS-1 added homework for Variables topic
Flex73/KotlinSprint pull request #6
Opened 2024-08-14 20:28 UTC by Flex73

2024-08-15 14:21 UTC, ievetrovdev requested changes
По оформлению пулл реквеста:
 - Префикс проекта с названием и номером урока задачи следует прописывать в названии пулл реквеста. Например, "KS-1-1 сделал то-то".
 - Название ветки также должно содержать префикс проекта с номером урока и задачи, чтобы они все были уникальны и в них можно было легко ориентироваться. Слова в названии веток разделяются дефисами. Например, “KS-1-1-create-smth”.

2024-08-15 14:21 UTC, ievetrovdev commented on src/main/kotlin/Main.kt
>      println(gratitudeMessage)
Тут у тебя лишние задания, для каждого задания свой файл. Их не нужно смешивать

чтобы правильно залить изменения, надо:
 - переключиться в Идее на нужную ветку
 - внести изменения и сделать коммит в эту ветку (следить чтобы в стейдж не добавились лишние задачи, которые не относятся к данной задаче)
 - отправить ссылку в бот на этот же пулл реквест к соответствующей задаче

2024-08-15 14:30 UTC, Flex73 commented on src/main/kotlin/Main.kt
>      println(gratitudeMessage)
Это не лишние изменения, это merge с текущим мастером

2024-08-15 21:32 UTC, Flex73 commented on src/main/kotlin/Main.kt
>      println(gratitudeMessage)
Разделил логику, перенёс код по отдельным файлам

2024-08-15 21:34 UTC, closed without merging

2024-08-16 07:08 UTC, ievetrovdev reviewed
Смотри, у тебя на одно задание должен быть один файл, только с этим заданием.
И не нужно сливать или закрывать ПР до проверки